esphome:
  name: esp-5ed02d
  platform: ESP8266
  board: d1_mini
  comment: Kitchen
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  power_save_mode: HIGH
  output_power: "12dB"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  scl: D1
  sda: D2
  scan: True
  
sensor:
  - platform: htu21d
    temperature:
      id: temp1
      name: "Kitchen Temperature"
    humidity:
      id: humidity1
      name: "Kitchen Humidity"
    update_interval: 60s

  - platform: absolute_humidity
    name: Kitchen Absolute Humidity
    temperature: temp1
    humidity: humidity1

  - platform: template
    name: "Kitchen Dew Point"
    unit_of_measurement: "°C"
    lambda: |-
      const float a = 17.27;   // const from https://planetcalc.com/248/
      const float b = 237.7;   // const from https://planetcalc.com/248/
      return ( (b * ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) )/( a - ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) ) ); 
    accuracy_decimals: 4
binary_sensor:
  - platform: gpio
    pin: D6
    name: "Kitchen PIR"
    device_class: motion