esphome:
  name: esp-23bd97
  platform: ESP8266
  board: esp01_1m
  comment: Kitchen (Cupboard under sink)
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  ap: {} # This spawns an AP with the device name and mac address with no password.


captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: "Kitchen Cupboard WiFi Signal"
    update_interval: 60s
  - platform: dht
    model: dht22
    pin: GPIO2
    temperature:
      name: "Kitchen Cupboard Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 10
    humidity:
      name: "Kitchen Cupboard Humidity"
      filters:
        - sliding_window_moving_average:
            window_size: 8
            send_every: 10
    update_interval: 6s
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Kitchen Cupboard IP Address"
    ssid:
      name: "Kitchen Cupboard Connected SSID"
    bssid:
      name: "Kitchen Cupboard Connected BSSID"