esphome:
  name: esp-b86884
  comment: Dev3 (ESP32-C3-Mini)
#  platformio_options:
#    board_build.flash_mode: dio        # This chip is a twat and gets stuck in boot loops quite regularly

esp32: # See https://esphome.io/components/esp32.html : Support for ESP32 variants such as the S2, S3 and C3 is still in development and there could be issues!
  board: lolin_c3_mini # Note: This is NOT an ESP8266!
#  board: esp32-s3-devkitc-1
#  variant: esp32c3 
#  framework:
#    type: arduino
  framework:
    type: esp-idf
    version: recommended
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .home

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  

captive_portal:

#light: # Onboard RGB NeoPixel
#  - platform: neopixelbus
#    id: myC3MiniBt_led
#    type: GRB
#    variant: WS2812
#    method: ESP32_RMT_1
#    num_leds: 1
#    pin: GPIO7
#    name: "My C3 Mini BT Led"
#    effects:
#      - addressable_rainbow:
#          name: Rainbow Effect With Custom Values
#          speed: 10
#          width: 50
          
i2c: 
  sda: 8
  scl: 10
  scan: True