esphome:
  name: esp-e5e990
  platform: ESP8266
  board: d1_mini
  comment: Lounge
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  power_save_mode: LIGHT
  output_power: "10dB"
  ap: {}
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

#interval:
#  - interval: 10s
#    then:
#      - logger.log: Hello. Ten seconds have passed!
      
#deep_sleep: # D0 (GPIO16) must be connected to RST
#  run_duration: 1min
#  sleep_duration: 2min

i2c:
  scl: D1
  sda: D2
  scan: True
  
sensor:
  - platform: wifi_signal
    name: "Lounge WiFi Signal"
    update_interval: 60s
  - platform: htu21d
    temperature:
      name: "Lounge Temperature"
      filters:
        - offset: -1.0  # This is a guess, the sensor reads consistently higher than others at all times
    humidity:
      name: "Lounge Humidity"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: D3 # GPIO0
    name: "Lounge PIR"
    device_class: motion
    

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Lounge IP Address"
    ssid:
      name: "Lounge Connected SSID"
    bssid:
      name: "Lounge Connected BSSID"