esphome:
  name: esp-a3c76a
  comment: Dev (with screen)
  platform: ESP8266
  board: d1_mini



wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .home
  ap: {} # This spawns an AP with the device name and mac address with no password.

  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80
  js_url: http://fitpc2i-2.home/esphome-custom/v1-custom.js
  version: 1

ota:
  - platform: esphome
    password: ""

#time:
#  - platform: homeassistant

###############

i2c:
  sda: D2
  scl: D1
  scan: True


globals:
  - id: total_edge_count
    type: int
    restore_value: no
    initial_value: "0"

sensor:
  - platform: qmc5883l
    address: 0x0D
    id: qmc5883l_mag
    #field_strength_x:
      
      # name: "QMC5883L Field Strength X"
      #internal: true  # Exclude from Home Assistant
    #field_strength_y:
      # name: "QMC5883L Field Strength Y"
      #internal: true  # Exclude from Home Assistant
    #field_strength_z:
      # name: "QMC5883L Field Strength Z"
      #internal: true  # Exclude from Home Assistant
    range: 200uT
    oversampling: 512x
    update_interval: 300s
#    internal: true



binary_sensor:
  - platform: gpio
    pin: D5
    name: "Edge Counter Binary Sensor"
    internal: true
    on_state:
      then:
        - component.update: qmc5883l_mag
        - lambda: |-
            id(total_edge_count) += 1;
        - logger.log: 
            format: "X: %u"
            args: ['id(total_edge_count)']



        
#  - platform: vl53l0x
#    id: vl53l0x_dist
#    address: 0x29
#    internal: true  # Exclude from Home Assistant
#    filters:
#      delta: 1000
#    update_interval: never
#    on_value:
#      then:
#        - component.update: qmc5883l_mag