esphome:
  name: esp_ada747
  platform: ESP8266
  board: d1_mini
  comment: Box room
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  power_save_mode: LIGHT
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


i2c:
  sda: D2
  scl: D1
  scan: True
  
sensor:
  - platform: sht3xd
    temperature:
      name: "Box Room Temperature"
    humidity:
      name: "Box Room Humidity"
    address: 0x44
    update_interval: 60s
  - platform: pulse_counter
    pin: D4
    name: Box room sound level    
    
binary_sensor:
  - platform: gpio
    pin: D3
    name: "Box Room PIR"
    device_class: motion
