esphome:
  name: esp-a3cf27
  platform: ESP8266
  board: d1_mini
  comment: Back bedroom
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "b41700748ae8d9309b5e774ec5fc9126"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Back bedroom IP Address"
    ssid:
      name: "Back bedroom Connected SSID"
    bssid:
      name: "Back bedroom Connected BSSID"

sensor:
  - platform: sht3xd
    temperature:
      name: "Back bedroom temperature"
    humidity:
      name: "Back bedroom humidity"
    address: 0x45
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Back bedroom PIR"
    device_class: motion
  
  
