esphome:
  name: esp-b86884
  comment: Dev3 (ESP32-C3-Mini)
#  platformio_options:
#    board_build.flash_mode: dio        # This chip is a twat and gets stuck in boot loops quite regularly
  on_boot:
    priority: -100 # Run this after other startup tasks
    then:
      - logger.log: "Booting up and executing on_boot automation!"
      - light.addressable_set:
          id: lightstrip1
          range_from: 0
          range_to: 50
          red: 66%
          green: 0%
          blue: 0%
#      - light.turn_on:
#          id: myC3MiniBt_led
#          effect: "Rainbow Effect With Custom Values"


esp32: # See https://esphome.io/components/esp32.html : Support for ESP32 variants such as the S2, S3 and C3 is still in development and there could be issues!
  board: lolin_c3_mini # Note: This is NOT an ESP8266!
#  board: esp32-s3-devkitc-1
#  variant: esp32c3 
#  framework:
#    type: arduino
#  framework:
#    type: esp-idf
#    version: recommended
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  domain: .home
  output_power: 8.5
  # No idea what generates this hostname, but without next line, ota will fail
  use_address: esp32c3-B86884
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  

captive_portal:

sensor:
  - platform: hx711
    name: "Load Cell"
    dout_pin: GPIO3
    clk_pin: GPIO4
    gain: 128
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 30151 -> 0.0
          - 61697 -> 20.0
          - 86139 -> 45.0
          - 137575 -> 95.0
          - 189346 -> 157.0
          - 257173 -> 215.0
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1
    state_class: "measurement"
    device_class: "weight"
    unit_of_measurement: g
    accuracy_decimals: 1
    
light:
#  - platform: neopixelbus
#    id: myC3MiniBt_led
#    type: GRB
#    variant: WS2812
#    method: ESP32_RMT_1
#    num_leds: 1
#    pin: GPIO7
#    name: "My C3 Mini BT Led"
#    effects:
#      - addressable_rainbow:
#          name: Rainbow Effect With Custom Values
#          speed: 10
#          width: 50

  - platform: neopixelbus
    id: lightstrip1
    type: BRG
    variant: WS2811
    method: ESP32_RMT_1
    num_leds: 50  #5m at 30 LED's per metre but each chip controls 3 LED's
    pin: GPIO6
    name: "LED Strip"
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - pulse:
      - strobe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - automation:
          name: Bike1
          sequence:
            - light.addressable_set:
                id: lightstrip1
                range_from: 0
                range_to: 12
                red: 50%
                green: 50%
                blue: 50%
#            - delay: 100ms
            - light.addressable_set:
                id: lightstrip1
                range_from: 13
                range_to: 27
                red: 50%
                green: 0%
                blue: 0%
#            - delay: 100ms
            - light.addressable_set:
                id: lightstrip1
                range_from: 28
                range_to: 40
                red: 50%
                green: 50%
                blue: 50%
            - light.addressable_set:
                id: lightstrip1
                range_from: 40
                range_to: 50
                red: 50%
                green: 0%
                blue: 0%


