esphome:
  name: esp-e5e990
  platform: ESP8266
  board: d1_mini
  comment: Lounge
  libraries:
    - Wire
    - SPI
    - "https://github.com/wemos/LOLIN_HP303B_Library.git"

external_components:
  - source: github://shish/esphome-projects
    components: [ hp303b ]
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .home
  power_save_mode: LIGHT
  output_power: "8.5dB"
  ap: {}
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

#web_server:
#  port: 80
  
time:
  - platform: homeassistant
    id: homeassistant_time

#interval:
#  - interval: 10s
#    then:
#      - logger.log: Hello. Ten seconds have passed!
      
#deep_sleep: # D0 (GPIO16) must be connected to RST
#  run_duration: 1min
#  sleep_duration: 2min

i2c:
  scl: D1
  sda: D2
  scan: True
  
sensor:
  - platform: sht3xd
    heater_enabled: false
    address: 0x45
    temperature:
      name: "Lounge Temperature"
      id: temp1
    humidity:
      name: "Lounge Humidity"
      id: humidity1
    update_interval: 60s

#  - platform: htu21d
#    address: 0x40
#    temperature:
#      name: "Lounge Temperature2"
#      id: temp2
#    humidity:
#      name: "Lounge Humidity2"
#      id: humidity2
#    update_interval: 60s

  - platform: hp303b # Make sure libraries for LOLIN_HP303B_Library.git are registered!
    address: 0x77
    temperature:
      name: "Lounge Temperature3"
      id: temp3
      device_class: TEMPERATURE
      accuracy_decimals: 1
    pressure:
      id: pressure1
      name: "Air Pressure"
      device_class: ATMOSPHERIC_PRESSURE
      unit_of_measurement: "mbar"
      accuracy_decimals: 4
    update_interval: 60s

  - platform: absolute_humidity
    name: Lounge Absolute Humidity
    temperature: temp1
    humidity: humidity1

  - platform: template
    name: "Lounge Dew Point"
    unit_of_measurement: "°C"
    lambda: |-
      const float a = 17.27;   // const from https://planetcalc.com/248/
      const float b = 237.7;   // const from https://planetcalc.com/248/
      return ( (b * ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) )/( a - ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) ) ); 
    accuracy_decimals: 1

#binary_sensor:
#  - platform: gpio
#    pin: D3 # GPIO0
#    name: "Lounge PIR"
#    device_class: motion
    

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Lounge IP Address"
    bssid:
      name: "Lounge Connected BSSID"