esphome:
  name: esp-a3c76a
  comment: Car (temp)
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  ap: {} # This spawns an AP with the device name and mac address with no password.

  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant



sensor:
  - platform: dht
    pin: D5
    model: AUTO_DETECT
    temperature:
      name: "Car Temperature"
    humidity:
      name: "Car Humidity"
    update_interval: 60s


  - platform: sht3xd 
    temperature:
      name: "Car Temperature2"
    humidity:
      name: "Car Humidity2"
    address: 0x45  
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "Car Temperature3"
    humidity:
      name: "Car Humidity3"
    update_interval: 60s

  - platform: dht
    pin: D6
    model: DHT22_TYPE2
    temperature:
      name: "Car Temperature4"
    humidity:
      name: "Car Humidity4"
    update_interval: 60s

i2c:
  scan: true
  scl: D1
  sda: D2

