esphome:
  name: esp-dd6bdc
  platform: ESP8266
  board: d1_mini
  comment: Summer house

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # Disable log output on the UART as it conflicts with use by modbus

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
time:
  - platform: homeassistant
    id: homeassistant_time


uart:
  - id: my_uart1
    baud_rate: 9600
    debug:
      direction: BOTH
    parity: none
    stop_bits: 1
    tx_pin: GPIO1 # TX pin
    rx_pin: GPIO3 # RX pin

modbus:
  id: modbus1
  uart_id: my_uart1
  flow_control_pin: D2 # GPIO4
  
modbus_controller:
  - id: growatt
    # the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10  



# My model: Growatt MIC 750 TL-X single phase inverter
# Protocol docs here? https://www.photovoltaicsolar.in/Growatt_Manual/MAX%20Series%20Modbus%20RTU%20Protocol.pdf
# or here: https://raw.githubusercontent.com/nygma2004/growatt2mqtt/main/Growatt%20PV%20Inverter%20Modbus%20RS485%20RTU%20Protocol%20v120.pdf
sensor:
  - platform: growatt_solar
    update_interval: 10s
    protocol_version: RTU2 # RTU or RTU2?

    inverter_status:
      name: "Growatt Status Code"

    phase_a:
      voltage:
          name: "Growatt AC Voltage Phase"
      current:
          name: "Growatt AC Current Phase"
      active_power:
          name: "Growatt AC Power Phase"
          state_class: measurement
          
    pv1:
      voltage:
          name: "Growatt PV Voltage"
      current:
          name: "Growatt PV Current"
      active_power:
          name: "Growatt PV Active Power"
          
#    active_power:
#      name: "Growatt Grid Active Power"

#    pv_active_power:
#      name: "Growatt PV Active Power"

    frequency:
      name: "Growatt Frequency"
      state_class: measurement
      filters: # This filter is needed because the inverter often sends erroneous values on startup
        - lambda: |-
            if (x < 45.0 || x > 55.0) {
              return {};
            }
            return x;

    energy_production_day:
      name: "Growatt Today's Generation"
      device_class: energy
      state_class: total_increasing

    total_energy_production:
      name: "Growatt Total Energy Production"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing

    inverter_module_temp:
      name: "Growatt Inverter Module Temp"
      filters: # This filter is needed because the inverter often sends erroneous values on startup
        - skip_initial: 3
        - filter_out: 0.0
      
      
  - platform: dht
    model: AM2302
    pin: D6
    temperature:
      name: "Shed Temperature"
      id: temp1
    humidity:
      name: "Shed Humidity"
      id: humidity1
    update_interval: 60s

  - platform: absolute_humidity
    name: Shed Absolute Humidity
    temperature: temp1
    humidity: humidity1

  - platform: template
    name: "Shed Dew Point"
    unit_of_measurement: "°C"
    lambda: |-
      const float a = 17.27;   // const from https://planetcalc.com/248/
      const float b = 237.7;   // const from https://planetcalc.com/248/
      return ( (b * ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) )/( a - ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) ) ); 
  