esphome:
  name: esp-e607e5
  platform: ESP8266
  board: d1_mini
  comment: Front bedroom
  
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


i2c:
  sda: D2
  scl: D1
  scan: True
  
sensor:
  - platform: sht3xd
    temperature:
      name: "Front bedroom temperature"
      id: temp1
    humidity:
      name: "Front bedroom humidity"
      id: humidity1
    address: 0x45
    update_interval: 60s

  - platform: absolute_humidity
    name: Front bedroom Absolute Humidity
    temperature: temp1
    humidity: humidity1

  - platform: template
    name: "Front bedroom Dew Point"
    unit_of_measurement: "°C"
    lambda: |-
      const float a = 17.27;   // const from https://planetcalc.com/248/
      const float b = 237.7;   // const from https://planetcalc.com/248/
      return ( (b * ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) )/( a - ( (id(temp1).state * a) / ( b + id(temp1).state) + logf (id(humidity1).state/100) ) ) ); 
    
binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Front bedroom PIR"
    device_class: motion
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Front bedroom IP Address"
    ssid:
      name: "Front bedroom Connected SSID"
    bssid:
      name: "Front bedroom Connected BSSID"