esphome:
  name: esp-a3cf27
  platform: ESP8266
  board: d1_mini
  comment: 3D printer
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "b41700748ae8d9309b5e774ec5fc9126"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .home
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: True

switch:
  - platform: gpio
    name: "3D Printer Relay"
    pin: D0
    
sensor:
  - platform: sht3xd
    temperature:
      name: "3D Printer temperature"
      id: temp1
    humidity:
      name: "3D Printer humidity"
      id: humidity1
    address: 0x45
    update_interval: 60s


  - platform: absolute_humidity
    name: 3D Printer Absolute Humidity
    temperature: temp1
    humidity: humidity1
