esphome:
  name: esp-3d3e68
  platform: ESP8266
  board: d1_mini
  

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan
  power_save_mode: LIGHT
  #output_power: "10dB"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant



sensor:
  - platform: dht
    pin: D5
    model: DHT22_TYPE2 # Didn't work: AUTO_DETECT, DHT11, DHT22
    temperature:
      name: "Hall Temperature"
    humidity:
      name: "Hall Humidity"
    update_interval: 60s

