esphome:
  name: esp-be1e8d
  comment: Dev2 (clock)
  
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  domain: .lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: MON
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 292;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: TUE
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 585;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: WED
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 878;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: THU
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 1170;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: FRI
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 1463;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: SAT
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 1755;'
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: SUN
        then:
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return 2048;'
            
#i2c:
#  scan: true
#  scl: D1
#  sda: D2

number:
  - platform: template
    name: Stepper Control
    min_value: -1024
    max_value: 1024
    step: 1
    set_action:
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return x;'
  - platform: template
    name: Stepper Angle
    min_value: 0
    max_value: 360
    step: 5
    set_action:
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return -x * 5.69f;'

select:
  - platform: template
    name: Day of week
    id: manual_day
    options:
     - "Off"
     - "Monday"
     - "Tuesday"
     - "Wednesday"
     - "Thursday"
     - "Friday"
     - "Saturday"
     - "Sunday"
    initial_option: "Off"
    optimistic: true
    on_value:
      then:
        - logger.log:
            format: "Chosen option: %s (index %d)"
            args: ["x.c_str()", "i"]    
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Monday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 292;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Tuesday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 585;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Wednesday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 878;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Thursday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 1170;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Friday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 1463;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Saturday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 1755;'
        - if:
            condition:
              lambda: 'return id(manual_day).state == "Sunday";'
            then:
              - stepper.set_target:
                  id: my_stepper
                  target: !lambda 'return 2048;'

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D8
    pin_b: D7
    pin_c: D6
    pin_d: D5
    sleep_when_done: true
    max_speed: 250 steps/s

    # Optional:
    acceleration: inf
    deceleration: inf